### ISSUE TITLE
Demo link is dead

### ISSUE THREAD

**Issue by picobots** [ghepting/jquery-responsive-tables#1]
The demo link for this project is a dead link. Is there a live link anywhere on the web where we can check this out?

**Comment by ghepting** [comment]
Ah yeah, I was doing some spring cleaning and nuked my website a bit prematurely -- I'll setup a codepen or something temporarily.

**Comment by ghepting** [comment]
Here ya go! Hacked it together pretty quick -- let me know if there's any bizarre behavior.  :)

http://codepen.io/ghepting/full/JomQVV/

Try it out in Flexy, my little viewport resizer:
http://ghepting.github.io/resizer/?url=http%3A%2F%2Fcodepen.io%2Fghepting%2Ffull%2FJomQVV%2F

**Comment by picobots** [comment]
Cool, thanks!
